# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='text',
            new_name='status_text',
        ),
    ]
